# Generated by Django 5.0.1 on 2024-01-10 06:03

import django.db.models.deletion
import notification.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_code', models.CharField(max_length=3, validators=[notification.validators.operator_code_validator])),
                ('tag', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=11, validators=[notification.validators.phone_number_validator])),
                ('time_zone', models.CharField(choices=[('<zip object at 0x7fac05f1d800>', 'Timezone')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_code', models.CharField(max_length=3, validators=[notification.validators.operator_code_validator])),
                ('tag', models.CharField(max_length=150)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Sent', 'Отправлено'), ('Rejected', 'Не доставлено'), ('Failed', 'Ошибка')])),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='notification.client')),
                ('mailing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing', to='notification.mailing')),
            ],
        ),
    ]
