# Generated by Django 5.0.1 on 2024-01-14 06:49

import notification.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.CharField(max_length=3, validators=[notification.validators.operator_code_validator], verbose_name='Код оператора'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.CharField(max_length=150, verbose_name='Ter'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='operator_code',
            field=models.CharField(max_length=3, validators=[notification.validators.operator_code_validator], verbose_name='Код оператора'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='tag',
            field=models.CharField(max_length=150, verbose_name='Ter'),
        ),
        migrations.AddConstraint(
            model_name='mailing',
            constraint=models.CheckConstraint(check=models.Q(('tag__isnull', True), _negated=True), name='validate_tag', violation_error_message='Данного тега не существует'),
        ),
        migrations.AddConstraint(
            model_name='mailing',
            constraint=models.CheckConstraint(check=models.Q(('operator_code__isnull', True), _negated=True), name='validate_operator_code', violation_error_message='Данного кода оператора не существует'),
        ),
    ]
